version: '3.8'

services:
  spark-master:
    image: spark-anonymizer:latest
    container_name: spark-master
    hostname: spark-master
    ports:
      - "8080:8080"  # Spark Web UI
      - "4040:4040"  # Spark Job Monitoring
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_PORT=7077
    volumes:
      - ./data:/data  # Mount local ./data folder to /data inside the container
    command: ["/opt/bitnami/scripts/spark/run.sh"]

  spark-worker:
    image: spark-anonymizer:latest
    container_name: spark-worker
    depends_on:
      - spark-master
    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER_URL=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=3.5G  # Allocate memory for larger datasets
      - SPARK_WORKER_CORES=2    # Allocate 4 cores per worker
    volumes:
      - ./data:/data  # Mount local ./data folder to /data inside the container
    command: ["/opt/bitnami/scripts/spark/run.sh"]
